name: Update README
# */30 * * * *
on:
  schedule:
    - cron: ''
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1.0
      - uses: ismailalabou/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
